### ISSUE TITLE
TheCocktailDB integration

### ISSUE THREAD

**Issue by SecularSteve** [MOIMOB/drinkable#353]
https://www.thecocktaildb.com/

Another open source solution for cocktails that happens to have a lot more drinks listed.

Two ways this can go about:

-Add it all manually
-Integrate the Database into the App itself

Of course, I'm making this suggestion with the intent that you're at least partially aware of it. It would be interesting to see their clunky site in a more consumable fashion. There's thousands of attempts on GitHub too with apps and web clients, but none of them seem as easy or efficient to use as your app.

But that's just my suggestion. Depending on the answer, I can try making a list/sheet of all the missing Cocktails currently present on the database.

**Comment by anton-gustafsson** [comment]
Hi! Thank you for opening this issue

I'm familiar with TheCocktailDB, a lot of cocktails used in Drinkable is import from there. However I did a lot of manual work to 'clean up' the data from the API so I don't really see a smooth way of integrating with the db itself. Here is some on top of my head improvements made in the app regarding data

* I have standardized the units to metric. This improves the user experience as units will not be mixed. And it also allows for easy conversion to Imperial.
* The data is locally stored in the app, so the app will work even without internet connection. 
* Drinkable have translations to more languages
* Inclusion of Cocktail Ingredients
* Categorized Ingredients into type of spirit
* Added support to have list of substitutes for ingredients 

 I want Drinkable to include more cocktails. It would be really helpful with a list of missing cocktails from TheCocktailDB. 

Love to hear from you!

**Comment by XayOn** [comment]
If anyone is willing, this is data gotten from https://github.com/lauriharpf/thecocktaildb-downloader and pre-parsed (just a bit) to:

- Be more like drinkable's format (yet, ingredients-by-id are not there, tags are strings, units are strings, because json)
- Use, whenever possible, mililliters (automatically translated, so there's a lot of pending manual work there)

But alas, it's a start, and reduces a bit the need for manual labor.

[drinkable.json.txt](https://github.com/MOIMOB/drinkable/files/12577813/drinkable.json.txt)
